### ISSUE TITLE
How to use secret

### ISSUE THREAD

**Issue by mdubs45** [itzmanish/ecr-token-renew#7]
Having some errors trying to use the ecr-renew-token chart. Below is the steps I completed in order to attempt to get ecr-renew-token working with my cluster

Below are my files that concern the image pulling from ECR

1. I overrode values in values.yaml
values.yaml
```
chart:
  configMapKeyRef: "my-configmap"
  dockerSecretName: "my-ecr"
```

2. I created a configmap to hold aws creds
configmap.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
    name: my-configmap
data:
    AWS_ACCESS_KEY_ID: "MY_ACCESS_KEY"
    AWS_SECRET_ACCESS_KEY: "MY_SECRET_ACCESS_KEY"
    AWS_REGION: "us-west-1"

```
I added permissions to allow the ecr-renew-container to create a secret
permissions.yaml
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: secrets-role
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: secrets-default
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secrets-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
```
4. I then used my secret as the image pull secret
queryrunner.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queryrunner
  labels:
    app: queryrunner
spec:
  selector:
    matchLabels:
      app: queryrunner
  replicas: 1
  template:
    metadata:
      name: queryrunner
      labels:
        app: queryrunner
    spec:
      containers:
        - name: queryrunner
          image: MY_ACCOUNT_IMAGE_URI
          imagePullPolicy: IfNotPresent

      imagePullSecrets:
        - name: "my-ecr"

```

Getting this error
```
  Normal   Pulling    2m51s (x4 over 10m)  kubelet            Pulling image "MY_ACCOUNT_IMAGE_URI"
  Warning  Failed     52s (x4 over 8m22s)  kubelet            Failed to pull image "MY_ACCOUNT_IMAGE_URI": rpc error: code = Unknown desc = context deadline exceeded
  Warning  Failed     52s (x4 over 8m22s)  kubelet            Error: ErrImagePull
  Warning  Failed     26s (x7 over 8m21s)  kubelet            Error: ImagePullBackOff
```
